package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"orchid-starter/gql/graph/generated"
	"orchid-starter/gql/graph/model"
)

// Welcome is the resolver for the welcome field.
func (r *queryResolver) Welcome(ctx context.Context) (*model.ResponseWelcome, error) {

	// db := r.DI.GetMySQL()
	// requestClient := r.DI.GetClient()
	// esClient := r.DI.GetElasticsearch()
	// pub := publisher.NewEventPublisher(r.DI.GetPublisher())

	// defaultRepository := repository.NewDefaultRepository(db, esClient, r.DI.GetTracer())

	// Initialize usecase with client access
	// uc := usecase.NewDefaultUsecase(db, defaultRepository, requestClient, pub, r.DI.GetTracer())
	// return &model.ResponseWelcome{
	// 	Message: uc.GetWelcome(ctx).Message,
	// }, nil
	return nil, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
